AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Layout:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
  Exclude:
    - bin/**/*
    - Gemfile

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false